# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
desc "Build XCFramework"
lane :build_xcframework do
  # Define paths and framework details
  project_root = "../" # Path to the folder containing your project and workspace
  output_dir = "../build" # Output directory outside the fastlane folder
  framework_name = "EnrollLite"
  workspace_name = "EnrollLite.xcworkspace"
  scheme_name = "EnrollLite"

  # Clean the build directory
  sh "rm -rf #{output_dir}"
  sh "mkdir -p #{output_dir}"

  # Build for iOS Simulator
  sh "xcodebuild archive -workspace #{project_root}#{workspace_name} \
      -scheme #{scheme_name} \
      -destination 'generic/platform=iOS Simulator' \
      -archivePath #{output_dir}/#{framework_name}-Sim \
      -configuration Release \
      SKIP_INSTALL=NO \
      BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
      ENABLE_BITCODE=NO"

  # Build for iOS Device
  sh "xcodebuild archive -workspace #{project_root}#{workspace_name} \
      -scheme #{scheme_name} \
      -destination 'generic/platform=iOS' \
      -archivePath #{output_dir}/#{framework_name}-iOS \
      -configuration Release \
      SKIP_INSTALL=NO \
      BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
      ENABLE_BITCODE=NO"

  # Create the XCFramework
  sh "xcodebuild -create-xcframework \
      -framework #{output_dir}/#{framework_name}-iOS.xcarchive/Products/Library/Frameworks/#{framework_name}.framework \
      -framework #{output_dir}/#{framework_name}-Sim.xcarchive/Products/Library/Frameworks/#{framework_name}.framework \
      -output #{output_dir}/#{framework_name}.xcframework"

  # Output success message
  UI.success("Successfully built #{framework_name}.xcframework at #{output_dir}")
end



end
